name: 知らせて.jp
permalink: /news/:year/:month/:title
relative_permalinks: false
excerpt_separator: "<!-- Read More -->"

paginate: 5
paginate_path: "news/page/:num"

# Prose settings
prose:
  rooturl: '_posts'
  siteurl: "http://info.shirasete.georepublic.net"
  relativeLinks: 'http://info.shirasete.georepublic.net/links.jsonp'
  media: "media"

  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"

      - name: "title"
        field:
          element: "text"

      - name: "date"
        field:
          element: "text"
          value: CURRENT_DATETIME

      - name: "author"
        field:
          element: "text"

      - name: "published"
        field:
          element: "checkbox"
          value: true

      - name: "tags"
        field:
          element: "multiselect"


